Ticket5
bashirzadehdanial/Front-End-NC-News pull request #2
Opened 2022-06-15 11:03 UTC by bashirzadehdanial

2022-06-15 11:23 UTC, emilyb93 commented on src/App.js
> +       <Route path='/topics/cooking' element={<CookingTopic />} />
We should not be hardcoding pages that are all set up the same. topics/coding football and cooking should all be one single route and one single element using a parametric path and useParams like this;

\<Route path='/topics/:topic_name' element={\<TopicPage>}> />

2022-06-15 11:28 UTC, emilyb93 requested changes
Refactor your pages so that you only use one page for listing out the topics for each of the topics. The page is the same for each, we should just fetch different data based on the page

2022-06-15 13:09 UTC, DCrawley94 requested changes
You're almost there on this one but notice how similar the `articles` and `parametricTopics` components are. You could combine this into a single component which would be much tidier!

Also I notice you're filtering the articles on the front end. Try to avoid this, you have queries on the backend that can do all the hard work for you!

2022-06-17 15:07 UTC, Augs0 approved these changes
Well done, Danial. This is looking good now :)

2022-06-17 15:21 UTC, merged